### ISSUE TITLE
Exception documentation

### ISSUE THREAD

**Issue by michael-schnell** [msemys/esjc#1]
It's hard to figure out what exceptions are thrown executing an operation. Currently the only way is to dive into the source code. It would be nice to add "@throws" javadoc to the AbstractEventStore or EventStore API. I know those are runtime exceptions but sometimes it's necessary to catch them and wrap them into other ones. 

**Background**: I'm currently trying to create a wrapper for your stuff for the [event-store-commons](https://github.com/fuinorg/event-store-commons) library. Your exceptions like 'WrongExpectedVersionException' have to be converted into the same named one in that library.

**Comment by msemys** [comment]
I'll try to enrich API documentation with client exceptions (when future completes exceptionally) for the next release.

**Comment by michael-schnell** [comment]
Cool.

**Comment by uweschaefer** [comment]
uups. i linked to #1 instead of #15. sry.
