### ISSUE TITLE
New Maven Central release 1.6.0

### ISSUE THREAD

**Issue by michael-schnell** [msemys/esjc#11]
Changing the "EventStore" class into an interface introduced an incompatible change and it would be nice to have a new release on Maven Central for that.

**Comment by msemys** [comment]
to be released next month

**Comment by michael-schnell** [comment]
Could you then provide a SNAPSHOT on Sonatype? Otherwise I'm not able to build my projects on Cloudbees until next month...

**Comment by michael-schnell** [comment]
Any news when to expect the next release?
