### ISSUE TITLE
Feature-Req: Creation, Deletion and Query of Projections

### ISSUE THREAD

**Issue by uweschaefer** [msemys/esjc#17]
I'd be nice to create EventStore-Side Projects and Query them from Java. Are there any plans of supporting this or similar Feature?

**Comment by msemys** [comment]
yes, it's on the list

**Comment by michael-schnell** [comment]
@uweschaefer It's not that hard - In the meantime you could take a look at this example: https://github.com/fuinorg/event-store-commons/blob/master/eshttp/src/main/java/org/fuin/esc/eshttp/ESHttpEventStore.java - See "createProjection(..)", "enableProjection(..)" and "disableProjection(..)".

**Comment by msemys** [comment]
projections management available in v1.8.0
