### ISSUE TITLE
Subscribe to Category or Array of Streams

### ISSUE THREAD

**Issue by uweschaefer** [msemys/esjc#18]
feeling bad to ask via an Issue, but i did not find any reference to a mailinglist or smth. please feel free to direct me to a more approriate place to ask questions like these.

Is there a way to subscribe to a number of Streams with one subscription call?

Background: Even though we could subscribe one listener to many streams by calling subscribe with the same listener, the overall order of the events would possibly be messed up. What i am trying to do is to subscribe to [foo-1, foo-2, foo-3,...] to get all events from all the foo-streams (like in the fromCategory({category}) in the projection examples), in the order they occurred.

Using wildcards would be even better like
[foo-.*, bar-.*, someStreamId, someOtherId]

is there any way to accomplish that, or something similar?

**Comment by msemys** [comment]
there is no such api for that, but you could try to subscribe to $all stream and filter events e.g.:
```java
eventstore.subscribeToAll(false, (s, e) -> {
    String streamId = e.originalStreamId();
    String category = (streamId.indexOf('-') != -1) ? 
        streamId.substring(0, streamId.indexOf('-')) : streamId;

    switch (category) {
        case "foo":
            // do something with event from 'foo-xxxx' stream
            break;
        case "bar":
            // do something with event from 'bar-xxxx' stream
            break;
        case "someStreamId":
            // do something with event from 'someStreamId' stream
            break;
        case "someOtherId":
            // do something with event from 'someOtherId' stream
            break;
    }
});
```

**Comment by uweschaefer** [comment]
thanks for taking the time to answer.

certainly true, that filtering can be done client side. problem is, that all events will be streamed to this subscription, which will kill startup time as well as network saturation, as we face a huge number of events and plenty of subscriptions.

It'd be nicer, if the filtering could be done server-side.

Is this an esjc issue, or an eventstore issue?

**Comment by msemys** [comment]
unfortunately, there is no such functionality to do filtering on server side.

**Comment by uweschaefer** [comment]
ah, ok. i'll turn to greg then with a feature request. thanks!

**Comment by uweschaefer** [comment]
look like, it is possible to subscribe to an array of streams?

https://geteventstore.com/blog/20130210/the-cost-of-creating-a-stream/

`fromStreams(["type-InventoryItemDeactived", "type-InventoryItemCreated"]).when( ... )`

that'd be exactly what i need. is there a way to get this through esjc?

**Comment by msemys** [comment]
no, it's impossible through TCP. `SubscribeToStream` message's field `event_stream_id` is not an array: 
https://github.com/EventStore/EventStore/blob/release-v4.0.0/src/Protos/ClientAPI/ClientMessageDtos.proto#L311

**Comment by uweschaefer** [comment]
crap. thanks!

**Comment by msemys** [comment]
another way, you could create projection, that collects events you need. and on the client-side subscribe to projection stream.

**Comment by uweschaefer** [comment]
yeah, but this projection has to be created at the server, so programmatic selection of event types is not possible. have to ponder the consequences a bit. thanks for sharing your thoughts!
