### ISSUE TITLE
Full support for EventStore 4.0.0

### ISSUE THREAD

**Issue by kristian-elder** [msemys/esjc#24]
Are there (short term) plans for upgrading event positions to 64 bit and any other changes required for full compatibility with EventStore 4?

**Comment by msemys** [comment]
Yes, EventStore 4 support will be added in the next major version (esjc v2.x)

**Comment by kristian-elder** [comment]
Thank you! Do you have any idea of timeline for this?

**Comment by msemys** [comment]
At the moment I'm working with the last esjc v1.x version, that will include projection support. After that, I will start with EventStore 4 support. So, I think esjc v2 will be released this summer.
