### ISSUE TITLE
Confirm compatibility of new release 4.1.0 

### ISSUE THREAD

**Issue by ontehfritz** [msemys/esjc#33]
Details here:
https://eventstore.org/blog/20180124/event-store-4.1.0-release/

**Comment by msemys** [comment]
esjc v2.0.0 is compatible with es v4.1.0 (you can see on [travis build report](https://travis-ci.org/msemys/esjc/builds/340554998) - all integration tests passed with es v4.1.0).

there is one feature added to es v4.1.0 client (`retryCount` field to `PersistentSubscriptionStreamEventAppeared` message) that I'll add on the next release.

**Comment by fritzcoder** [comment]
Great thank you very much! Keep up the great work. Your library is very useful :) Far exceeds the semi-official one.
