### ISSUE TITLE
iterateStreamEventsForward - Preserved Order Guaranty

### ISSUE THREAD

**Issue by jselamy** [msemys/esjc#47]
Hi,
Wanted to know what guaranty we have on the order (sorted based on eventNumber) events in a specific stream ?

Is there any ?

**Comment by jezovuk** [comment]
From quick code inspection, it seems that events are always returned in order according to event number (ascending for iterate/streamForward, descending for iterate/streamBackward).

**Comment by jselamy** [comment]
@jezovuk fair enough! I'll look over my code again.
