### ISSUE TITLE
Enhance WrongExpectedVersionException with expected and actual version

### ISSUE THREAD

**Issue by michael-schnell** [msemys/esjc#5]
The exception should contain the expected version (requested) and the actual version (stream had). This would allow better exception handling. The construction of the exception's message could then be moved into the exception class itself.

**Comment by msemys** [comment]
There is no such info about actual version of stream in operation result message received from server (when operation fails due wrong expected version).

**Comment by msemys** [comment]
Closing this issue for now

**Comment by michael-schnell** [comment]
The current version was added with this [commit](https://github.com/EventStore/EventStore/pull/959/commits/3c75f8e6766f3e05e62c6d01eacd59deb209d5c5) for version 3.7.0 of the event store. The 'WriteEventsCompleted' message should now contain a field 'CurrentVersion'.

**Comment by msemys** [comment]
it was added for http. 
tcp client still has no such field https://github.com/EventStore/EventStore/blob/release-v4.0.0/src/Protos/ClientAPI/ClientMessageDtos.proto#L56

**Comment by michael-schnell** [comment]
Hmmm... I thought they added it for both APIs... No I added a new [feature request](https://github.com/EventStore/EventStore/issues/1052) to include it also in the proto client message. Maybe you could reopen this issue to solve it after the new feature is available?
