### ISSUE TITLE
Enhance doc of "StreamMetadataResult.isStreamDeleted"

### ISSUE THREAD

**Issue by michael-schnell** [msemys/esjc#6]
The comment on the meta data result's field"isStreamDeleted" is somehow confusing. It states "Indicates whether or not the stream is soft-deleted." but it does not say which way round - Does TRUE mean "SOFT" or "HARD" deleted?

I created an [example](https://github.com/fuinorg/event-store-commons/blob/master/esjc/src/test/java/org/fuin/esc/esjc/NativeDeleteTest.java) to investigate this and it seems that TRUE actually means "HARD DELETED".

So I suggest adjusting the comment a bit:
"Indicates whether or not the stream is hard deleted (TRUE) or soft deleted (FALSE)."

**Comment by msemys** [comment]
The current description is correct.

In your example you are not waiting while "appendToStream" and "deleteStream" operations completes.
it should be:
```java
...
es.appendToStream(streamId, ExpectedVersion.any(), events).join();
es.deleteStream(streamId, ExpectedVersion.any(), true).join();
...
```

**Comment by michael-schnell** [comment]
You're right, I forgot to wait for the future, but the result is still somehow wrong:

I do a 'hard' delete:
`es.deleteStream(streamId, ExpectedVersion.any(), true).join();`
but the meta data returns it was a "soft" delete:
```
StreamMetadataResult result = es.getStreamMetadata(streamId).get();
if (result.isStreamDeleted) {
    // === THIS IS PRINTED ===
    System.out.println("SOFT DELETED");
}
```

**Comment by msemys** [comment]
at the moment documentation is the same as in .net client: https://github.com/EventStore/EventStore/blob/release-v4.0.0/src/EventStore.ClientAPI/StreamMetadataResult.cs#L16

I agree, it's confusing.. I think we can replace it with "Indicates whether or not the stream is deleted."
