### ISSUE TITLE
Replace installation in '.travis.yml' with Maven plugins

### ISSUE THREAD

**Issue by michael-schnell** [msemys/esjc#8]
Currently it's not possible just to check out the project and run "clean install". This will fail because the event store must be downloaded manually and the protobuf classes must be created manually.

Therefore I'd suggest replacing the ',travis,yml' installation part with real Maven plugins:
- [event-store-maven-plugin](https://github.com/fuinorg/event-store-maven-plugin)
- [protobuf-maven-plugin](https://github.com/xolstice/protobuf-maven-plugin)

I can take over that task if you want. I just prepared the release 0.4.1 of my event-store-maven-plugin that will support creating a self-signed certificate on the fly. Should be avialable in a few hours on Maven Central.

**Comment by msemys** [comment]
I would prefer not to depend on not mandatory plugins that are essential for building, testing and releasing the driver.

**Comment by michael-schnell** [comment]
The main problem was, that someone who checksout your project will not be able to build it at all. The general convention for Maven based builds is, that you can just checkout the project and run "mvn clean install". Your build does not work this way, because it's based on Travis specific stuff. 

What is the problem about using other Maven plugins for the build? This is normal as it does not make much sense to re-invent the wheel for already existing stuff.
